### ISSUE TITLE
[US02] Cadastrar aluno.

### ISSUE THREAD

**Issue by Peh099** [fga-eps-mds/2023.1-Amis-Doc#10]
### Descrição
Eu como Assistente social / Professor / Supervisor da Produção, desejo cadastrar aluno para que eu possa registrar o controle dos dados dos alunos e para que eu possa cadastrar uma instrução da produção ou alocá-lo em uma produção

### Quem pode cadastrar Aluno?
- Admin do sistema
- Assistente social
- Professor

### Campos

- Login: chave primária
- Nome do aluno: String com máximo de 70 caracteres
- Data de nascimento: 
       - Validar mês, dia e ano;
- CPF:
       - Validar cpf conforme a regra de validação geral para cpf.
- Telefone: o número deve estar no formato DDD + 9 digitos conforme padrão nacional
- Email (opcional): deve estar no formato 'texto@texto.com'
- Senha: verificar se a senha possui mais que 8 caracteres
- Status do aluno:
     - ENUM: Produção, Curso ou Inativo.
           - Esse ENUM servirá para verificar se o aluno está tendo aulas de um curso, se ele é um ex-aluno que está na parte de Produção ou se ele está inativo (já foi aluno mas não atua mais).
     - Esse status deve ser setado automaticamente no cadastro do aluno para Curso
     - Esse status pode ser editado a qualquer momento pelo professor, assistente social ou administrador do sistema.
- Deficiencia: verificar se possui alguma deficiência.
- Bairro:  String com máximo de 100 caracteres.
- Cep: String com máximo de 8 caracteres.  
- Cidade: String com máximo de 100 caracteres.
- Descricao_endereco: String com máximo de 200 caracteres.

### Pré-requisitos:
Sem pré-requisitos

### Microsserviço
- Usuario

### Tarefas:

1. [Frontend] Interface de cadastro do aluno  @LorrayneCardozo  @eric-kingu @Peh099 
2. [Backend] CRUD do aluno:   @lorranyoliveira @caioalvesbraga @Erick-ems 

### Critérios de Aceitação 
- [ ] O sistema deve permitir que o assistente social cadastre um novo aluno. Para isso, deve haver uma interface onde o assistente social ou professor possa informar login de acesso, nome completo do aluno, cpf, data de nascimento, telefone, email e senha.

- [ ] O sistema deve validar as informações inseridas pelo assistente social/professor, garantindo que as informações colocadas em 'Campos' sejam válidas.

- [ ] O sistema deve prover uma interface para que o assistente social/professor consulte as informações dos alunos cadastrados, caso seja necessário.

- [ ] O sistema deve prover uma interface para que o assistente social/professor edite as informações dos alunos cadastrados, caso seja necessário.

- [ ] O sistema deve prover uma interface para que o assistente social/professor exclua alunos cadastrados, caso seja necessário.

- [ ] O sistema deve, após o cadastro com sucesso, colocar o status inicial do aluno como 'Curso'.

### Protótipo:
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1&t=eJr7zhXBAAMmC8Ud-0

**Comment by gpersijn** [comment]
Autor do refinamento técnico para tirar dúvidas: @gpersijn

**Comment by AntonioAldisio** [comment]
@gpersijn , se possível, coloque o link do repositorio do microserviço. Assim fica mais fácil para saber onde será desenvolvido o codigo
