### ISSUE TITLE
[US10] Matricular aluno em turma 

### ISSUE THREAD

**Issue by lorranyoliveira** [fga-eps-mds/2023.1-Amis-Doc#11]
### Descrição
Eu como assistente social desejo matricular aluno em turma para que eu possa para definir quais alunos irão compor uma turma.

### Quem pode matricular aluno em Turma?
- Professor
- Admin do sistema
- Assistente social

### Campos
- Nome do aluno: String máxima 70 caracteres.
- Data criação (Aluno): String máx 70 caracteres.
- CPF (Aluno).

### Pré-requisitos
[#10 ] Cadastrar Aluno
[#12 ] Cadastrar Turma

### Microsserviço:
- [Curso](https://github.com/fga-eps-mds/2023.1-Amis-ClassroomService)

### Tarefas:

1. [Frontend] Interface para visualização dos alunos cadastrados e escolha do aluno que será cadastrado. @marialuisa214 @GustavoAPS
7. Testes unitários Front. @GustavoAPS 

### Critérios de Aceitação.
- [ ] O sistema deve permitir que o assistente social/professor cadastre alunos na turma.

- [ ] O sistema deve permitir que o assistente social/professor remova alunos na turma.

- [ ] O sistema deve prover de uma interface que eu liste todos os alunos cadastrados após clicar em adicionar novo aluno.

**Comment by Peh099** [comment]
Autor do refinamento técnico para tirar dúvidas: @Peh099

**Comment by AntonioAldisio** [comment]
@Peh099, se possível, coloque o link do repositorio do microserviço. Assim fica mais fácil para saber onde será desenvolvido o codigo
