### ISSUE TITLE
[US09] Cadastrar turma.

### ISSUE THREAD

**Issue by Peh099** [fga-eps-mds/2023.1-Amis-Doc#12]
### Descrição
Eu como Assistente Social desejo cadastrar turma para que eu possa alocar alunos da turma.

### Quem pode cadastrar Turma?
- Admin do sistema
- Assistente social
- Professor

### Campos

- Código: chave primária
- Nome da turma: String (max 70 caracteres)
- Data:
       - Data de início: deve ser antes da data de fim
       - Data de fim: deve ser depois da data de inicio
- Horário:
      - Inicio da aula: horário de inicio deve ser antes do horário de fim
      - Fim da aula: horário de fim deve ser depois do horário de inicio
      - O horário informado deve estar entre 00:00 e 23:59
- Capacidade da turma: Int > 0
- Curso: Enumerar Cursos cadastrados no sistema .
- Professor: Enumerar Professores cadastrados no sistema. 

### Pré-requisitos
[#10] Cadastrar Professor

### Microsserviço
- [Curso](https://github.com/fga-eps-mds/2023.1-Amis-ClassroomService)

### Tarefas:

1. [Frontend] Interface para cadastro de uma nova turma (conforme os campos e validações especificadas) @gaubiela 
2. [Frontend] Interface para visualização das turmas cadastradas. @gaubiela 
3. [Backend] CRUD da turma (Create/Método: POST e DELETE).@FilhoDoan 
4. [Backend] CRUD da turma (Read/Método: GET).  @FilhoDoan @GustavoAPS 
5. [Backend] CRUD da turma (Update/Método: PUT). @GustavoAPS 
6*. [Backend] Consumir alunos e professores do UserService. 
7. Testes automatizados Front. 
8. Testes automatizados Back. @GustavoAPS  
  

### Critérios de Aceitação
- [x] O sistema deve permitir que o assistente social cadastre turma para alocar curso, professor e alunos. Para isso, deve haver uma interface onde o assistente social possa informar a data de inicio, a data de fim, o horário de início e fim das aulas, capacidade da turma, o Curso da turma, o Professor responsável pela turma.

- [ ] O sistema pode cadastrar uma turma sem ter nenhum aluno alocado.

- [ ] O sistema deve permitir que o assistente social/professor cadastre posteriormente alunos na turma. (#11)

- [ ] O sistema deve validar as informações inseridas pelo assistente social/professor, garantindo as regras de negócio detalhadas abaixo em 'Campos'.

- [ ] O sistema deve prover de uma interface para que eu possa listar todas as turmas cadastradas e acessar as informações de cada turma. 

- [ ] O sistema deve prover de uma interface para que eu possa apagar alguma turma cadastrada.

- [ ] O sistema deve prover de uma interface para que eu possa editar alguma turma cadastrada.

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1

**Comment by gpersijn** [comment]
Autor do refinamento técnico para tirar dúvidas: @gpersijn

**Comment by AntonioAldisio** [comment]
@gpersijn , se possível, coloque o link do repositorio do microserviço. Assim fica mais fácil para saber onde será desenvolvido o codigo
