### ISSUE TITLE
[US05] Fazer login

### ISSUE THREAD

**Issue by lorranyoliveira** [fga-eps-mds/2023.1-Amis-Doc#15]
### Descrição
Eu como Usuario desejo fazer login na plataforma para acessar os serviços e funcionalidades do sistema

### Quem pode fazer Login?
- Admin do sistema
- Assistente social
- Professor
- Aluno
- Supervisor de Produção

### Campos

- Login: chave primária dos usuários 
- Senha: caracter de no mínimo 8 digitos

### Pré-requisitos:
[#8 ou #19 ou #10 ...] Ter um usuário já cadastrado

### Microsserviço
- Usuario

### Tarefa:
[Back-end] Endpoint login - @marialuisa214 
[Back-end] Gerar JWT - @gaubiela 
[Back-end] Verificar e renovar token - @CauaMatheus 
[Back-end] Testes unitários - @GustavoAPS 

### Critérios de Aceitação 
- [x] O sistema deve fornecer uma página de login onde o usuário possa inserir seu login de usuário e senha.
- [x] Se o nome de usuário e a senha inseridos estiverem corretos, o sistema deve permitir que o usuário acesse os serviços e funcionalidades.
- [x] Se o nome de usuário e a senha inseridos estiverem incorretos, o sistema deve exibir uma mensagem de erro indicando que as credenciais estão incorretas e permitir que o usuário tente novamente
- [ ] O sistema deve armazenar as credenciais do usuário com segurança e proteger contra ataques de força bruta ou tentativas de hacking
- [ ] O sistema deve fornecer ao usuário um token de acesso JWT após a autenticação bem-sucedida.
- [ ] O sistema deve verificar a validade do token de acesso JWT em todas as solicitações subsequentes.
- [ ] O sistema deve renovar o token de acesso JWT automaticamente antes da expiração, para que o usuário não precise fazer login novamente.

**Comment by gpersijn** [comment]
Autores do refinamento técnico disponível para dúvidas: @gpersijn e @Peh099
