### ISSUE TITLE
[US06] Fazer logout

### ISSUE THREAD

**Issue by Peh099** [fga-eps-mds/2023.1-Amis-Doc#17]
### Descrição
Eu, como Usuário, desejo fazer logout na plataforma para que eu possa sair de maneira segura da plataforma.

### Quem pode fazer logout?
- Admin do sistema
- Assistente social
- Professor
- Aluno
- Supervisor de Produção

### Pré-requisitos:
- [#15] Fazer login na plataforma

### Microsserviço
- Usuario

### Tarefas:
[Back-end] Criar classe de persistência para logout - @FilhoDoan @caio-lelis 
[Back-end] Criar testes unitários - @gpersijn 

### Critérios de Aceitação 
- [x] O sistema deve permitir que o usuário encerre a sessão ou desconecte-se do sistema de forma segura. 
- [ ] O usuário deve ser capaz de fazer logout em qualquer página da plataforma.
- [ ] Quando o usuário faz logout, todas as sessões ativas devem ser encerradas.
- [ ] Depois de fazer logout, o usuário deve ser redirecionado para a página de login.
- [ ] Se o usuário tentar acessar qualquer página da plataforma após fazer logout, ele deve ser redirecionado para a página de login.
- [ ] O logout deve ser facilmente acessível e claramente visível na interface do usuário.
- [ ] Deve haver uma confirmação de que o logout foi bem-sucedido.
- [ ] O sistema deve permitir que o usuário faça logout e revogue o token de acesso JWT atual.

**Comment by LorrayneCardozo** [comment]
Autores do refinamento técnico disponível para dúvidas: @gpersijn, @Peh099 e @LorrayneCardozo
