### ISSUE TITLE
[US03] Cadastrar Professor

### ISSUE THREAD

**Issue by Peh099** [fga-eps-mds/2023.1-Amis-Doc#19]
### Descrição
Eu como Assistente Social desejo cadastrar professor para que eu possa atribuí-lo o papel de cadastrar instruções para os alunos e cadastrá-lo em uma Turma.

### Quem pode cadastrar Professor?
- Admin do sistema
- Assistente social

### Campos

- Código: chave primária
- Nome do professor: String com máximo de 70 caracteres
- Data de nascimento: 
       - Validar mês, dia e ano;
       - Validar se a idade da pessoa é maior que 18.
- CPF:
       - Validar cpf conforme a regra de validação geral para cpf.
- Telefone: o número deve estar no formato DDD + 9 digitos conforme padrão nacional
- Email (opcional): deve estar no formato 'texto@texto.com'
- Cursos (opcional): pode aparecer uma aba para ele selecionar Cursos já cadastrados no banco de dados e selecionar quais ele ministra.
- Observações: String com máximo de 70 para indicar observações (Nao poder dar aula aos sábados, por exemplo.)
- Senha: verificar se a senha possui mais que 8 caracteres

### Pré-requisitos:
[#9] Cadastrar Curso

### Microsserviço
- User
 
### Critérios de Aceitação.
- [x] O sistema deve permitir que o assistente social cadastre um novo professor. Para isso, deve haver uma interface onde o assistente social possa informar nome completo do professor, cpf, data de nascimento, telefone, email e a(s) área(s) de atuação desse professor.

- [x] O sistema deve validar as informações inseridas pelo assistente social, garantindo que as informações colocadas em 'Campos' sejam válidas.

- [ ] O sistema deve prover uma interface para que o assistente social consulte as informações dos professores cadastrados, caso seja necessário.

- [ ] O sistema deve prover uma interface para que o assistente social ou o professor edite as informações dos professores cadastrados, caso seja necessário.

- [ ] O sistema deve prover uma interface para que o assistente social exclua professores cadastrados, caso seja necessário.

**Comment by gpersijn** [comment]
Autor do refinamento técnico disponível para dúvidas: @gpersijn

**Comment by marioandunb** [comment]
Validado!
