### ISSUE TITLE
Criação do .gitignore

### ISSUE THREAD

**Issue by Peh099** [fga-eps-mds/2023.1-Amis-Doc#3]
**Em que documento a refatoração é necessária?**
 
Novo Documento

**Explique, de forma clara, o motivo pelo qual o documento deve ser refatorado:**

Ainda não existe um documento .gitigonore para a nossa documentação, sendo esse necessário para evitar futuros problemas.

**Qual o estado atual do documento?**

Documento precisa ser criado

**Qual o estado desejado do documento após a refatoração?**

Inicialmente o .gitignore deve incluir todos os documentos .DS_STORE. Observem que existem mais de um documento ".DS_STORE" dentro de sub-pastas. 

**Critérios Aceitação**  
- [x] Documento .gitignore criado.
- [x] Arquivos .DS_STORE não inclusos no gitpages.

**Comment by gaubiela** [comment]
Tasks concluidas. 

https://github.com/fga-eps-mds/2023.1-Amis-Doc/commit/5e9bd12d4c334ab0b5cadefe415f01660d0c88bc
