### ISSUE TITLE
[US13] Cadastrar Supervisor de Produção

### ISSUE THREAD

**Issue by gpersijn** [fga-eps-mds/2023.1-Amis-Doc#65]
### Descrição
Eu, como  Assistente Social, desejo cadastrar Supervisor de Produção para que eu possa atribuí-lo o papel de agendamento de centros produtivos

### Quem pode cadastrar Supervisor da Produção?
- Admin do sistema
- Assistente social

### Campos

- Login: chave primária
- Nome do supervisor: String com máximo de 70 caracteres
- Data de nascimento:
      - Validar mês, dia e ano;
      - Validar se a idade da pessoa é maior que 18.
- CPF:
      - Validar cpf conforme a regra de validação geral para cpf.
- Telefone: o número deve estar no formato DDD + 9 digitos conforme padrão nacional
- Email (opcional): deve estar no formato 'texto@texto.com'
- Senha: verificar se a senha possui mais que 8 caracteres

### Pré-requisitos
Sem pré-requisitos

### Microsserviço
- [UserService](https://github.com/fga-eps-mds/2023.1-Amis-UserService)

### Tarefas:

1. [backend] Criar service e model de supervisor da produção
2. [backend] Endpoint POST supervisor de produção
3. [backend] Endpoint GET e GETALL supervisor de produção
4. [backend] Endpoint PUT supervisor de produção
5. [backend] Endpoint DELETE supervisor de produção
6. [backend] Endpoint LOGIN para supervisor de produção
7. [frontend] Criar tela de cadastro de supervisor de produção com a chamada para o endpoint POST
8. [frontend] Criar tela de visualização de supervisor de produção com a chamada para os endpoints PUT,DELETE E GETALL

### Critérios de Aceitação
- [ ] O sistema deve permitir que o assistente social cadastre supervisor de produção. Para isso, deve haver uma interface onde o assistente social possa informar os campos atribuídos na sessão Campos desse docmento.
- [ ] O assistente social deve conseguir cadastrar um supervisor da produção sem os campos opcionais.
- [ ] O assistente social deve receber mensagem de erro caso tenha algum campo obrigatório não preenchido.
- [ ] O assistente social deve receber mensagem de erro caso tenha algum campo obrigatório preenchido incorretamente.
- [ ] O sistema deve validar as informações inseridas pelo assistente social/admin, garantindo todas as regras de negócio detalhadas em 'Campos'.
- [ ] O sistema deve prover de uma interface para que eu possa listar todos os supervisores da produção cadastrados e acessar as informações de cada supervisor. 
- [ ] O sistema deve prover de uma interface para que eu possa apagar algum supervisor da produção cadastrado.
- [ ] O sistema deve prover de uma interface para que eu possa editar alguma turma cadastrado.

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1

**Comment by marioandunb** [comment]
Validado!
