### ISSUE TITLE
[US14] Cadastrar Centro Produtivo

### ISSUE THREAD

**Issue by gpersijn** [fga-eps-mds/2023.1-Amis-Doc#66]
### Descrição
Eu, como Assistente social / Supervisor da Produção, desejo cadastrar Centro Produtivo disponível para que eu possa disponibilizar sua alocação para os ex-alunos.

### Quem pode cadastrar Centro Produtivo?
- Admin do sistema
- Assistente social
- Supervisor da Produção

### Campos

- Codigo: chave primária
- Descricao: String com máximo de 170 caracteres
- Data agendada:
      - Validar mês, dia e ano;
- Status:
      - Disponível ou Indisponível

### Pré-requisitos
Sem pré-requisitos

### Microsserviço
- [Production](https://github.com/fga-eps-mds/2023.1-Amis-ProductionService)

### Tarefas:

1. [backend] Criar service e model do centro produtivo
2. [backend] Endpoint POST supervisor de produção
3. [frontend] Criar tela de cadastro de centro produtivo com a chamada para o endpoint POST

### Critérios de Aceitação
- [ ] O sistema deve permitir que o assistente social ou o supervisor da produção cadastre centro produtivo. Para isso, deve haver uma interface onde o assistente social/supervisor possa informar os campos atribuídos na sessão Campos desse docmento.
- [ ] O assistente social deve receber mensagem de erro caso tenha algum campo obrigatório não preenchido.
- [ ] O assistente social deve receber mensagem de erro caso tenha algum campo obrigatório preenchido incorretamente.
- [ ] O sistema deve validar as informações inseridas pelo assistente social/professor, garantindo todas as regras de negócio detalhadas em 'Campos'.

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1

**Comment by marioandunb** [comment]
Acredito que o horizonte temporal deva incluir uma perspectiva de "turno" (manhã ou tarde ou noite), e não apenas o "dia".
