### ISSUE TITLE
[US15] Visualizar lista de Centros Produtivos disponíveis

### ISSUE THREAD

**Issue by gpersijn** [fga-eps-mds/2023.1-Amis-Doc#67]
### Descrição
Eu, como Assistente social / Supervisor da Produção, desejo visualizar Centro Produtivo disponível para que eu possa disponibilizar sua alocação para os ex-alunos.

### Quem pode cadastrar Centro Produtivo?
- Admin do sistema
- Assistente social
- Supervisor da Produção

### Campos

- Codigo: chave primária
- Descricao: String com máximo de 170 caracteres
- Data agendada:
      - Validar mês, dia e ano;
- Status:
      - Disponível ou Indisponível

### Pré-requisitos
Sem pré-requisitos

### Microsserviço
- [Production](https://github.com/fga-eps-mds/2023.1-Amis-ProductionService)

### Tarefas:

1. [backend] Criar service e model do centro produtivo (verificar se ja foi feito com a US #14)
2. [backend] Endpoint PUT, DELETE, GET e GETALLL de centro produtivo
3. [frontend] Criar tela de visualização de centro produtivo com a chamada para o endpoint PUT, DELETE, GETALL

### Critérios de Aceitação

- [ ] O sistema deve prover uma interface para que o assistente social ou supervisor consulte as informações dos centros produtivos cadastrados, caso seja necessário.
- [ ]  O sistema deve prover uma interface para que o assistente social ou supervisor edite as informações dos centros cadastrados, caso seja necessário.
- [ ]  O sistema deve prover uma interface para que o assistente social ou supervisor exclua professores cadastrados, caso seja necessário.
- [ ] O sistema deve validar as informações inseridas pelo assistente social/supervisor, garantindo todas as regras de negócio detalhadas em 'Campos' no caso de Edição.

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1

**Comment by marioandunb** [comment]
Chamaria a storie de "Disponibilidade dos Centros Produtivos"
