### ISSUE TITLE
[US18] Validar aluno no centro produtivo

### ISSUE THREAD

**Issue by gpersijn** [fga-eps-mds/2023.1-Amis-Doc#70]
### Descrição
Eu, como Assistente Social / Supervisor da Produção, desejo validar aluno no centro produtivo para que eu possa confirmar sua inscrição .

Nessa tarefa, na tela de listagem do centro produtivo, deve haver um novo botão que abrirá uma nova tela de listagem dos alunos que foram inscritos naquele centro produtivo. Nessa tela, o supervisor poderá remover ou confirmar os alunos que se inscreveram. 

PARA MELHOR VISUALIZAÇÃO, ACESSE PARA O PROTÓTIPO DE BAIXA FIDELIDADE:
https://excalidraw.com/#room=55247d1c0674e0546c9e,VoEWgeoNMAzuY9n7sSyFNQ
(Pressione a tecla de espaço e arraste com o mouse para mover a tela mais facilmente)

### Quem pode validar aluno do centro produtivo?
- Assistente Social
- Supervisor da Produção

### Campos
- Nomes do aluno: String máxima 70 caracteres. 
   - Deve ser feita a listagem dos alunos que foram cadastados pelo banco
   
### Pré-requisitos
CRUD Centro Produtivo

### Microsserviço
- [Production](https://github.com/fga-eps-mds/2023.1-Amis-ProductionService)

### Tarefas:

1. [frontend] Botão na tela de listagem dos centros produtivos (Como referência tem o botão de ver alunos da Turma)
2. [frontend] Tela de listagem dos alunos que foram matriculados
     - Essa tela deve conter todos os nomes dos alunos que se inscreveram, consultar endpoint GETALL
4. [frontend] Essa tela deve os botões de exclusão de um aluno ->Endpoint DELETE
5. [frontend] Deve poder selecionar um ou mais alunos para a exclusão (Como referência tem a tela de alunos na Turma)
3. [backend] Criar endpoint retornando todos os nomes dos alunos que estão naquele centro produtivo -> Consultar do banco tabela que associa a chave do Centro Produtivo e do Aluno
4. [backend] Confirmar se tem o endpoint de DELETE

### Critérios de Aceitação
- [ ] O supervisor deve ver todos os alunos que foram cadastrados naquele centro produtivo
- [ ] O supervisor deve excluir um aluno do agendamento do centro produtivo

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1

**Comment by marioandunb** [comment]
Validado!
