### ISSUE TITLE
[US01] Cadastrar Assistente social.

### ISSUE THREAD

**Issue by lorranyoliveira** [fga-eps-mds/2023.1-Amis-Doc#8]
### Descrição
Eu como Admin do sistema/Assistente Social desejo cadastrar assistente social para que eu possa atribuí-la o papel de gerenciar as permissões de acesso às funcionalidades do sistema.

### Quem pode cadastrar Assistente Social?
- Admin do sistema

### Campos
- Login: chave primária
- Nome da assistente social: String com máximo de 70 caracteres
- Data de nascimento: 
       - Validar mês, dia e ano;
- CPF:
       - Validar cpf conforme a regra de validação geral para cpf.
- Telefone: o número deve estar no formato DDD + 9 digitos conforme padrão nacional
- Email (opcional): deve estar no formato 'texto@texto.com'
- Senha: verificar se a senha possui mais que 8 caracteres

### Pré-requisitos:
Sem pré-requisitos

### Microsserviço
- Usuario

### Tarefas:

1. [Frontend] Interface de cadastro da assistente social: @LorrayneCardozo @FHansen98 @Erick-ems 
2. [Backend] CRUD da assistente social: @biancasofia @iagorrr04

### Critérios de Aceitação 
- [x] O sistema deve permitir que o admin do sistema cadastre uma nova assistente social. Para isso, deve haver uma interface onde o admin do sistema possa informar login de acesso, nome completo da assistente social, cpf, data de nascimento, telefone, email e senha.

- [x] O sistema deve validar as informações inseridas pelo admin do sistema, garantindo que as informações colocadas em 'Campos' sejam válidas.

- [x] O sistema deve prover uma interface para que o admin consulte as informações dos assistentes sociais cadastrados, caso seja necessário.

- [x] O sistema deve prover uma interface para que o admin edite as informações dos assistentes sociais cadastrados, caso seja necessário.

- [x] O sistema deve prover uma interface para que o admin exclua assistentes sociais cadastrados, caso seja necessário.

### Protótipo:
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1&t=eJr7zhXBAAMmC8Ud-0

**Comment by gpersijn** [comment]
Autores do refinamento técnico disponível para dúvidas: @gpersijn e @Peh099

**Comment by AntonioAldisio** [comment]
@Peh099 e @gpersijn , se possível, coloque o link do repositorio do microserviço. Assim fica mais fácil para saber onde será desenvolvido o codigo

**Comment by iagorrr** [comment]
Padrões adotados durante o desenvolvimento no **backend** para se receber os seguintes campos.

| campo | tipo | formato | comentário|
| - | - | - |
| data | str | YYYY-DD--MM | ISO 8601 |
| cpf | str | 12345678911 | somente dígitos |
| telefone | str | ... | 11 dígitos, dois primeiros para DDD|
