### ISSUE TITLE
[US07] Cadastrar curso

### ISSUE THREAD

**Issue by lorranyoliveira** [fga-eps-mds/2023.1-Amis-Doc#9]
### Descrição
Eu como Assistente Social desejo cadastrar curso para que eu possa criar turmas em que serão ministradas aulas de determinado curso.

### Quem pode cadastrar Curso?
- Admin do sistema
- Assistente social
- Professor

### Campos

- idCurso: chave primária
- Nome do curso: String com máximo de 70 caracteres
- Descrição: String com máximo de 300 caracteres
- Duração de horas: int (valor em horas) 

### Pré-requisitos
Sem pré-requisitos

### Microsserviço
- [Classroom Service](https://github.com/fga-eps-mds/2023.1-Amis-ClassroomService)

### Tarefas
1. [Frontend] Interface de cadastro de curso:  @biancasofia, @Erick-ems, @iagorrr 
2. [Backend] CRUD de curso: @biancasofia, @Erick-ems, @iagorrr 
3. Testes do back: @biancasofia, @iagorrr 

### Critérios de Aceitação.
- [x] O sistema deve permitir que o assistente social crie cursos para posteriormente criar turmas. Para isso, deve haver uma interface onde o assistente social possa informar o nome do curso, a descrição do curso e a carga horária do curso.

- [x] O usuário tem a opção de excluir um curso existente.
- [x] Ao confirmar a exclusão, o curso é removido permanentemente do sistema.
- [x] O usuário pode editar os detalhes do curso, como nome, descrição e duração.
- [x] As alterações feitas pelo usuário devem ser salvas e refletidas no sistema.
- [x] Ao editar os detalhes do curso, o sistema deve realizar validações para garantir que os campos obrigatórios sejam preenchidos corretamente.
- [x] A funcionalidade de visualizar, excluir e editar dados do curso deve ser restrita a usuários autenticados e autorizados.

### Protótipo
https://www.figma.com/file/UWVRKI0dvYnnF6lYI76Vzy/AMIS-team-library?type=design&node-id=0-1&t=tRobm3xR5Vm86FbY-0

**Comment by gpersijn** [comment]
Autor do refinamento técnico disponível para dúvidas: @gpersijn

**Comment by marioandunb** [comment]
Gostaria de sugerir que a duração do curso fosse colocada em horas e não semanas. A ideia é que cada curso possua diversas turmas, é isso?

**Comment by AntonioAldisio** [comment]
@gpersijn , se possível, coloque o link do repositorio do microserviço. Assim fica mais fácil para saber onde será desenvolvido o codigo
